'Packages completed' string should use P_() instead of N_().
Prevents this:

    Traceback (most recent call first):
      File "/tmp/updates/yuminstall.py", line 214, in callback
        self.numpkgs)
    TypeError: <lambda>() takes exactly 1 argument (3 given)