Fix crash because of missing import statement
Fixes:

pyanaconda.errors.ExitError: gnome-kiosk exited on signal 5
Exception ignored in atexist callback:
Traceback (most recent call last):
  File "/sbin/anaconda", line 73, in exitHandler
    sync_run_task(task_proxy)
    ^^^^^^^^^^^^^

NameError: name 'sync_run_task' is not defined

This was a regression by ecae47.

Resolves https://bugzilla.redhat.com/show_bug.cgi?id=2240087