Revert "Fix lang-name generation"
This reverts commit a6ba02f4099c40f3dd2c2783cf0bac2c1900ade4.

This currently breaks lang-names generation.  We see this in the
build.log in koji:

PYTHONPATH="." python2.5 scripts/getlangnames.py > lang-names
Traceback (most recent call last):
  File "scripts/getlangnames.py", line 37, in <module>
    names[langs.localeInfo[k][0]] = cat.lgettext(langs.localeInfo[k][0])
  File "/usr/lib/python2.5/gettext.py", line 368, in lgettext
    return tmsg.encode(locale.getpreferredencoding())
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

I'm just a simple back country hyperchicken, not a Unicode expert.