pyanaconda: module_manager: fix ciclic import
E   ImportError: cannot import name 'ModuleObserver' from partially initialized module
'pyanaconda.modules.boss.module_manager' (most likely due to a circular import)
(/tmp/anaconda/pyanaconda/modules/boss/module_manager/__init__.py)