TypeError: argument must be string (#1209414)
We tried to show exception object instead of string.
Now the exception is changed to string.

Resolves: rhbz#1209414