TypeError: '_ped.DiskType' object is not callable (#531730)
platform.X86.__init__ did: self.diskLabelType = foo instead of
self._diskLabelType = foo. So it was overriding the method from the
base class.