pyanaconda: module.common.task fix cyclic import
Fixing this error:

unit_tests/pyanaconda_tests/__init__.py:34: in <module>
    from pyanaconda.modules.common.task import TaskInterface
../pyanaconda/modules/common/task/__init__.py:21: in <module>
    from pyanaconda.modules.common.task.meta import DBusMetaTask
../pyanaconda/modules/common/task/meta.py:19: in <module>
    from pyanaconda.modules.common.task import AbstractTask
E   ImportError: cannot import name 'AbstractTask' from partially initialized module 'pyanaconda.modules.common.task' (most likely due to a circular import) (/tmp/anaconda/pyanaconda/modules/common/task/__init__.py)

Related: RHEL-85416