Catch race of network device state vs reading its config properties (#980576)
Catch the infamous

DBusException: org.freedesktop.DBus.Error.UnknownMethod:
Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties"
doesn't exist

exception.

Object with path from devices's IPXConfig property is valid only if
its device is in ACTIVATED state.