Fix ci-tasks container shell instructions
With the variable reorg in commit a452f1bac0, `CI_TASKS_TEST_ARGS`
already contains the volume mount and `--rm`, so it's not necessary any
more to repeat it -- in fact, that fails:

    Error: /anaconda: duplicate mount destination