Get DMRaidArrayDevice's a DiskLabel format when they are added to the tree
We were waiting for DMRaidArrayDevice's to be scanned before giving them
a DiskLabel format, however this causes backtraces if a partition on the
raid array gets scanned before the array itself:
AttributeError: 'DeviceFormat' object has no attribute 'partedDisk'