pyanaconda: bootloader: fix ImportError
ImportError: cannot import name 'BootLoaderFactory' from partially initialized module
(cherry picked from commit 98b1a6368efc7a45995d1b55e67216090d318f3c)

Related: RHEL-85416