Only install liveinst symlink on supported arches
The symlink to consolehelper from /usr/bin/liveinst should only be done
on arches with liveinst support, otherwise you will get an error when
trying to build:

error: Installed (but unpackaged) file(s) found:
   /usr/bin/liveinst

Related: rhbz#1121678
(cherry picked from commit 57832f704ad7f692b3ffeaf70880e8845d32a062)

Related: rhbz#1196721