pyanaconda: module_manager: fix ciclic import
E   ImportError: cannot import name 'ModuleObserver' from partially initialized module
'pyanaconda.modules.boss.module_manager' (most likely due to a circular import)
(/tmp/anaconda/pyanaconda/modules/boss/module_manager/__init__.py)

(cherry picked from commit 4166b0a3c687fb6f410785df7024fba1c55a62a9)

Related: RHEL-85415