Set the correct permissions for forks (#infra)
Fork has lower permissions as external contributor which in this case is
an issue because labeler needs to have also the `checks: write` set.

Without this change PRs from forks are getting:
```
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```