Fix unit test dependency installation for boolean expressions
Installing test dependencies in the documented way breaks due to boolean
dependencies:

```
$ sudo dnf install (./scripts/testing/dependencyₛolver.py)
Last metadata expiration check: 1:09:39 ago on Wed Sep 30 08:09:56 2020.
Packge kbd-2.3.0-2.fc33.x86_64 is already installed.
[...]
No match for argument: (glibc-langpack-en
No match for argument: or
No match for argument: glibc-all-langpacks)
[...]
Error: Unable to find a match: (glibc-langpack-en or glibc-all-langpacks)
```

There is no way how to quote spaces in package names that makes them
survive correctly through `$()`, so move to a line based format and feed
the list to dnf and setup-mock-test-env.py via `xargs`.